### ISSUE TITLE
cli.py not installed

### ISSUE THREAD

**Issue by stuartlynne** [puckdoug/zpdatafetch#1]
The cli.py script is not getting installed as zpdata.

Seems to work if copied to (e.g.) /usr/local/bin/zpdata

**Comment by puckdoug** [comment]
Thanks. Let me have a look what's up.

**Comment by puckdoug** [comment]
So, I'd been playing with uv for replacing the build chain which meant I wound up making some other changes. In any case, I've rebuilt and republished version 1.1.2. 

I've tested on Mac/windows/linux systems and it seems to work across all 3. I did notice one case where it appeared to fail: when the site_packages are not writable (e.g. python installed by root). In that case pip dropped the package into my local site packages, which happened not to be in my path. 

Whether because of the change in build tools or some other reason it appears on my side to be working. If you're still having issues, could you let me know a bit more about your setup so I can try to reproduce?

**Comment by mhgit** [comment]
How do you test it @puckdoug ?

`(3.12) martinh@zen-imac eracing % uv pip install zpdatafetch
Resolved 20 packages in 2.07s
   Built zpdatafetch==1.1.2
Prepared 20 packages in 1.37s
Installed 20 packages in 57ms
 + anyio==4.4.0
 + beautifulsoup4==4.12.3
 + certifi==2024.7.4
 + h11==0.14.0
 + httpcore==1.0.5
 + httpx==0.27.2
 + idna==3.8
 + iniconfig==2.0.0
 + jaraco-classes==3.4.0
 + jaraco-context==6.0.1
 + jaraco-functools==4.0.2
 + keyring==25.3.0
 + keyrings-alt==5.0.2
 + lxml==5.3.0
 + more-itertools==10.4.0
 + pip==24.2
 + pluggy==1.5.0
 + sniffio==1.3.1
 + soupsieve==2.6
 + zpdatafetch==1.1.2
`

**Comment by mhgit** [comment]
Quick test:
`(3.12) martinh@zen-imac eracing % which zpdata
/Users/martinh/3.12/bin/zpdata
(3.12) martinh@zen-imac eracing % zpdata -h
usage: zpdata [-h] [-v] [{config,cyclist,primes,result,signup,team}] [id ...]

Module for fetching zwiftpower data using the Zwifpower API

positional arguments:
  {config,cyclist,primes,result,signup,team}
                        which command to run
  id                    the id to search for, ignored for config

options:
  -h, --help            show this help message and exit
  -v, --verbose         provide feedback while running
`

**Comment by puckdoug** [comment]
@mhgit - I'm assuming /Users/martinh/3.12 is your venv directory? If you've got a current uv, you should also be able to simply execute `uv run zpdata -h` but the above appears good. Thanks.

@stuartlynne - I'm going to mark this done, but please do come back if it's not working on your end and let me know more about your environment so we can figure it out.

**Comment by mhgit** [comment]
martinh@zen-imac eracing % source ~/3.12/bin/activate
(3.12) martinh@zen-imac eracing % uv run zpdata -h          
error: No `project` table found in: `/Users/martinh/git-work/eracing/pyproject.toml`

**Comment by mhgit** [comment]
> @mhgit - I'm assuming /Users/martinh/3.12 is your venv directory? If you've got a current uv, you should also be able to simply execute `uv run zpdata -h` but the above appears good. Thanks.
> 
> @stuartlynne - I'm going to mark this done, but please do come back if it's not working on your end and let me know more about your environment so we can figure it out.

I ditched venv...
